import PDFDocument from 'pdfkit';
import { Response } from 'express';
import { IAppointment } from '../models/Appointment.js';
import { IOwner } from '../models/Owner.js';

export const generateAppointmentPdf = (
  res: Response,
  owner: IOwner,
  appointments: IAppointment[],
  titleStr: string = "Appointment History Report"
): void => {
  const doc = new PDFDocument({ margin: 50 });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="appointments_${Date.now()}.pdf"`);

  doc.pipe(res);

  // Header
  doc.fillColor('#059669').fontSize(22).text('CareSync Platform', { align: 'left' });
  doc.fillColor('#111827').fontSize(14).text(`Business: ${owner.outletName} (${owner.fullName})`);
  doc.fontSize(10).fillColor('#4B5563').text(`Category: ${owner.title} | Location: ${owner.district ? owner.district + ', ' : ''}${owner.state}, ${owner.country}`);
  doc.text(`Generated Date: ${new Date().toLocaleDateString()}`);
  doc.moveDown();

  doc.strokeColor('#E5E7EB').lineWidth(1).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
  doc.moveDown();

  // Document Title
  doc.fillColor('#111827').fontSize(16).text(titleStr, { underline: true });
  doc.moveDown(0.5);

  doc.fontSize(10).text(`Total Records: ${appointments.length}`);
  doc.moveDown();

  // Table Headers
  const tableTop = doc.y;
  doc.font('Helvetica-Bold');
  doc.text('Date', 50, tableTop, { width: 70 });
  doc.text('Slot/Token', 120, tableTop, { width: 70 });
  doc.text('Customer Name', 190, tableTop, { width: 110 });
  doc.text('Age/Gender', 300, tableTop, { width: 70 });
  doc.text('Reason', 370, tableTop, { width: 110 });
  doc.text('Status', 480, tableTop, { width: 70 });

  doc.font('Helvetica');
  let y = tableTop + 20;

  appointments.forEach((apt) => {
    if (y > 700) {
      doc.addPage();
      y = 50;
    }

    const slotOrToken = apt.appointmentMode === 'TOKEN' ? `#${apt.tokenNumber}` : (apt.appointmentTime || 'N/A');

    doc.fillColor('#374151').fontSize(9);
    doc.text(apt.appointmentDate, 50, y, { width: 70 });
    doc.text(slotOrToken, 120, y, { width: 70 });
    doc.text(apt.customerName, 190, y, { width: 110 });
    doc.text(`${apt.age} / ${apt.gender.charAt(0)}`, 300, y, { width: 70 });
    doc.text(apt.reason.length > 20 ? apt.reason.substring(0, 20) + '...' : apt.reason, 370, y, { width: 110 });
    
    // Status color
    let statusColor = '#374151';
    if (apt.status === 'CONFIRMED' || apt.status === 'COMPLETED') statusColor = '#059669';
    if (apt.status === 'CANCELLED' || apt.status === 'REJECTED') statusColor = '#DC2626';
    if (apt.status === 'PENDING') statusColor = '#D97706';

    doc.fillColor(statusColor).text(apt.status, 480, y, { width: 70 });

    y += 20;
  });

  // Footer
  doc.fontSize(8).fillColor('#9CA3AF').text('Generated by CareSync Verified Appointment Engine. Privacy Protected.', 50, 750, { align: 'center' });

  doc.end();
};
