// In-memory data store providing instant seeding and zero-delay mock API data when MongoDB is offline/downloading

export const memoryStore = {
  categories: [
    { _id: 'cat_1', name: 'Doctor', icon: 'Stethoscope', description: 'Certified physicians, cardiologists, pediatricians, & specialists', isActive: true, slug: 'doctor' },
    { _id: 'cat_2', name: 'Dentist', icon: 'Smile', description: 'Dental checkups, root canals, alignment, & cosmetic dentistry', isActive: true, slug: 'dentist' },
    { _id: 'cat_3', name: 'Salon', icon: 'Scissors', description: 'Hair styling, grooming, spa treatments, & beauty parlors', isActive: true, slug: 'salon' },
    { _id: 'cat_4', name: 'Gym', icon: 'Dumbbell', description: 'Fitness centers, weight training, & wellness clubs', isActive: true, slug: 'gym' },
    { _id: 'cat_5', name: 'Consultant', icon: 'Briefcase', description: 'Business strategy, financial advice, & career counseling', isActive: true, slug: 'consultant' },
    { _id: 'cat_6', name: 'Lawyer', icon: 'Scale', description: 'Legal advisory, corporate law, family law, & litigation', isActive: true, slug: 'lawyer' },
    { _id: 'cat_7', name: 'Tutor', icon: 'BookOpen', description: 'Academic tutoring, language learning, & entrance prep', isActive: true, slug: 'tutor' },
    { _id: 'cat_8', name: 'Mechanic', icon: 'Wrench', description: 'Automobile repair, diagnostic tuning, & engine overhaul', isActive: true, slug: 'mechanic' },
  ],

  owners: [
    {
      _id: 'owner_1',
      userId: 'user_owner_1',
      fullName: 'Dr. Rahul Sharma',
      email: 'doctor@example.com',
      mobile: '+91 9988776655',
      title: 'Senior Cardiologist & Internal Medicine Specialist',
      description: 'Over 15 years of clinical expertise treating complex cardiovascular disorders. Trained at premier medical institutions with state-of-the-art diagnostic facilities.',
      categoryId: { _id: 'cat_1', name: 'Doctor', icon: 'Stethoscope', slug: 'doctor' },
      secondaryCategoryIds: [],
      profileImage: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
      bannerImages: [
        'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=1200&auto=format&fit=crop&q=80',
      ],
      outletName: 'City Care Cardiology Center',
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      address: 'Suite 402, Hazratganj Medical Enclave, Lucknow, UP',
      appointmentMode: 'TIME',
      slotDurationMinutes: 30,
      dailyCapacity: 50,
      workingHours: [
        { day: 'Monday', isOpen: true, openTime: '09:00', closeTime: '17:00' },
        { day: 'Tuesday', isOpen: true, openTime: '09:00', closeTime: '17:00' },
        { day: 'Wednesday', isOpen: true, openTime: '09:00', closeTime: '17:00' },
        { day: 'Thursday', isOpen: true, openTime: '09:00', closeTime: '17:00' },
        { day: 'Friday', isOpen: true, openTime: '09:00', closeTime: '17:00' },
        { day: 'Saturday', isOpen: true, openTime: '09:00', closeTime: '13:00' },
        { day: 'Sunday', isOpen: false, openTime: '09:00', closeTime: '13:00' }
      ],
      activeStatus: 'ACTIVE',
      verificationStatus: 'VERIFIED',
      kycStatus: 'VERIFIED',
      kycProvider: 'InstantID Compliant KYC Provider',
      kycReferenceId: 'KYC-88492019',
      verifiedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'owner_2',
      userId: 'user_owner_2',
      fullName: 'Priya Verma',
      email: 'priya@glamstudio.com',
      mobile: '+91 9811223344',
      title: 'Master Hair Stylist & Aesthetician',
      description: 'Luxury hair styling, organic skincare rituals, and bridal couture styling with over 10 years of boutique studio experience.',
      categoryId: { _id: 'cat_3', name: 'Salon', icon: 'Scissors', slug: 'salon' },
      secondaryCategoryIds: [],
      profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&auto=format&fit=crop&q=80',
      bannerImages: [
        'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1200&auto=format&fit=crop&q=80',
      ],
      outletName: 'Glamour Lounge & Spa',
      country: 'India',
      state: 'Delhi',
      district: 'South Delhi',
      address: 'Plot 14, Greater Kailash Part 2, New Delhi',
      appointmentMode: 'TOKEN',
      slotDurationMinutes: 30,
      dailyCapacity: 30,
      workingHours: [
        { day: 'Monday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
        { day: 'Tuesday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
        { day: 'Wednesday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
        { day: 'Thursday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
        { day: 'Friday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
        { day: 'Saturday', isOpen: true, openTime: '10:00', closeTime: '20:00' },
        { day: 'Sunday', isOpen: true, openTime: '10:00', closeTime: '18:00' }
      ],
      activeStatus: 'ACTIVE',
      verificationStatus: 'VERIFIED',
      kycStatus: 'VERIFIED',
      kycProvider: 'InstantID Compliant KYC Provider',
      kycReferenceId: 'KYC-90412847',
      verifiedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'owner_3',
      userId: 'user_owner_3',
      fullName: 'Dr. Amit Mehta',
      email: 'amit@smileclinic.com',
      mobile: '+91 9822334455',
      title: 'Orthodontist & Cosmetic Dentist',
      description: 'Specialist in dental implants, clear aligners, and pain-free laser dentistry using world-class technology.',
      categoryId: { _id: 'cat_2', name: 'Dentist', icon: 'Smile', slug: 'dentist' },
      secondaryCategoryIds: [],
      profileImage: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
      bannerImages: [
        'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?w=1200&auto=format&fit=crop&q=80',
        'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=1200&auto=format&fit=crop&q=80',
      ],
      outletName: 'Apex Dental & Maxillofacial Care',
      country: 'India',
      state: 'Maharashtra',
      district: 'Mumbai',
      address: 'G-04, Bandra Kurla Complex, Mumbai, MH',
      appointmentMode: 'TIME',
      slotDurationMinutes: 30,
      dailyCapacity: 40,
      workingHours: [
        { day: 'Monday', isOpen: true, openTime: '09:00', closeTime: '18:00' },
        { day: 'Tuesday', isOpen: true, openTime: '09:00', closeTime: '18:00' },
        { day: 'Wednesday', isOpen: true, openTime: '09:00', closeTime: '18:00' },
        { day: 'Thursday', isOpen: true, openTime: '09:00', closeTime: '18:00' },
        { day: 'Friday', isOpen: true, openTime: '09:00', closeTime: '18:00' },
        { day: 'Saturday', isOpen: true, openTime: '09:00', closeTime: '14:00' },
        { day: 'Sunday', isOpen: false, openTime: '09:00', closeTime: '14:00' }
      ],
      activeStatus: 'ACTIVE',
      verificationStatus: 'VERIFIED',
      kycStatus: 'VERIFIED',
      kycProvider: 'InstantID Compliant KYC Provider',
      kycReferenceId: 'KYC-11029384',
      verifiedAt: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'owner_4',
      userId: 'user_owner_4',
      fullName: 'Adv. Ananya Roy',
      email: 'ananya@roylegal.com',
      mobile: '+91 9744556677',
      title: 'Corporate Legal Advisor & IPR Advocate',
      description: 'Providing legal consulting for startups, intellectual property filings, contract vetting, and commercial arbitration.',
      categoryId: { _id: 'cat_6', name: 'Lawyer', icon: 'Scale', slug: 'lawyer' },
      secondaryCategoryIds: [],
      profileImage: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&auto=format&fit=crop&q=80',
      bannerImages: [
        'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=1200&auto=format&fit=crop&q=80',
      ],
      outletName: 'Roy & Associates Legal Firm',
      country: 'India',
      state: 'Karnataka',
      district: 'Bengaluru',
      address: 'Level 5, MG Road Financial Tower, Bengaluru, KA',
      appointmentMode: 'TIME',
      slotDurationMinutes: 45,
      dailyCapacity: 20,
      workingHours: [
        { day: 'Monday', isOpen: true, openTime: '10:00', closeTime: '18:00' },
        { day: 'Tuesday', isOpen: true, openTime: '10:00', closeTime: '18:00' },
        { day: 'Wednesday', isOpen: true, openTime: '10:00', closeTime: '18:00' },
        { day: 'Thursday', isOpen: true, openTime: '10:00', closeTime: '18:00' },
        { day: 'Friday', isOpen: true, openTime: '10:00', closeTime: '18:00' },
        { day: 'Saturday', isOpen: false, openTime: '10:00', closeTime: '14:00' },
        { day: 'Sunday', isOpen: false, openTime: '10:00', closeTime: '14:00' }
      ],
      activeStatus: 'ACTIVE',
      verificationStatus: 'PENDING',
      kycStatus: 'PENDING',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ],

  appointments: [
    {
      _id: 'apt_1',
      userId: 'user_demo_1',
      ownerId: 'owner_1',
      categoryId: 'cat_1',
      customerName: 'Rahul Kumar',
      age: 28,
      gender: 'Male',
      phone: '+91 9123456789',
      reason: 'Routine cardiovascular checkup & ECG review',
      appointmentDate: new Date().toISOString().split('T')[0],
      appointmentTime: '10:30 AM',
      appointmentMode: 'TIME',
      status: 'CONFIRMED',
      ownerNotes: 'Patient requested morning follow-up call.',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    }
  ]
};
